# Default config file for the echo server
default: &default
    server:

    logging:

    database:
        name: echo
        user: echo
        host: server
        port: 5432

    auth:
        key_expires: 604800  # 1 week
        key_size: 8192  # Big key size for good message security

development:
    <<: *default
